// Shared by the game and the offline editor. No eval and no executable custom effects.
(()=>{'use strict';const fields={monsters:['attribute','species','rank','passives','nativeRecords','notes'],resistances:['element','status'],skills:['description','customEffect','element','type','target','side','power','cost','hits','status','statusChance','heal','healRate','buff','debuff','duration','selfHeal','selfBuff','guard','partyGuard','evasion','crit','splash','drain','cleanseChance','partyHeal','mpHeal','partyBuff','selfGuard','selfCleanse','ignoreEvasion','lowHpScale'],records:['theme','attribute','milestones'],fusions:['a','b','result','condition','requiredLineage','grantLineage','reason'],recordFusions:['a','b','result','condition'],passives:['効果']};
const copy=x=>JSON.parse(JSON.stringify(x)),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),safe=v=>{if(v&&typeof v==='object'){for(const k of Object.keys(v)){if(['__proto__','prototype','constructor'].includes(k))return false;if(!safe(v[k]))return false;}}return true;};
function entities(d){return {monsters:d.monsters.map(m=>({id:m.id||'monster:'+m.no,name:m.name,image:m.image,value:m})),resistances:d.monsters.map(m=>({id:m.id||'monster:'+m.no,name:m.name,image:m.image,value:d.resistances[m.name]})),skills:Object.values(d.skills).map(s=>({id:s.id||'skill:'+s.name,name:s.name,image:d.monsters.find(m=>(m.sourceSkills||[]).some(x=>(x.name||x.special)===s.name))?.image||d.monsters.find(m=>m.nativeRecords.some(n=>d.records.find(r=>r.name===n)?.milestones.some(t=>t.type==='SKILL'&&t.reward===s.name)))?.image,value:s})),records:d.records.map(r=>({id:r.id,name:r.name,image:d.monsters.find(m=>m.nativeRecords.includes(r.name))?.image,value:r})),fusions:d.fixedFusions.map(r=>({id:'fusion:'+r.no,name:r.a+' × '+r.b,image:d.monsters.find(m=>m.name===r.result)?.image,value:r})),recordFusions:d.recordFusions.map((r,i)=>({id:'record-fusion:'+encodeURIComponent(r.a)+'|'+encodeURIComponent(r.b),name:r.result,image:null,value:r})),passives:d.passives.map(p=>({id:p.ID,name:p.パッシブ,image:null,value:p}))};}
function validate(d,patch){const errors=[],warnings=[];if(!patch||patch.schemaVersion!==1||!Array.isArray(patch.ops)||patch.ops.length>5000||!safe(patch))return{errors:['差分形式が不正です。'],warnings};const clone=copy(d),tables=entities(clone),seen=new Set(),names=new Set(d.monsters.map(m=>m.name)),records=new Set(d.records.map(r=>r.name)),passives=new Set(d.passives.map(p=>p.パッシブ)),attrs=['無','火','水','雷','地','風','光','闇'];
 for(const op of patch.ops){const key=[op.entity,op.id,op.field].join('|'),item=tables[op.entity]?.find(x=>x.id===op.id);if(seen.has(key)){errors.push(key+': 重複変更');continue;}seen.add(key);if(!item||!fields[op.entity]?.includes(op.field)||!Object.hasOwn(op,'value')||!Object.hasOwn(op,'before')){errors.push(key+': 未対応のID/項目');continue;}if(!same(item.value[op.field]??null,op.before)){errors.push(item.name+': 元データが変わっています');continue;}const v=op.value,f=op.field,bad=why=>errors.push(item.name+' / '+f+': '+why);
 if(v===null||v===undefined||typeof v==='string'&&!v.trim()&&!['customEffect','notes','requiredLineage','grantLineage','status'].includes(f)){bad('空値は保存できません');continue;}
 if(['description','customEffect','notes','theme','効果','condition','requiredLineage','grantLineage','reason'].includes(f)&&(typeof v!=='string'||v.length>4000))bad('4000文字以下の文章を指定');
 if(['element','attribute'].includes(f)&&op.entity!=='resistances'&&!attrs.includes(v))bad('属性が不正');
 if(f==='rank'&&!d.rankOrder.includes(v))bad('ランクが不正');if(f==='species'&&!['スライム','ビースト','ネイチャー','アクア','ドラゴン','デーモン','マシン','マテリアル','ヒューマノイド','ボス'].includes(v))bad('種族が不正');
 if(op.entity==='resistances'){const keys=f==='element'?attrs:['毒','やけど','眠り','マヒ','ひるみ','混乱'];if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).length!==keys.length||keys.some(k=>!['F','E','D','C','B','A','S','SS'].includes(v[k])))bad('全耐性をF～SSで指定');}
 if(['passives','nativeRecords'].includes(f)){const ref=f==='passives'?passives:records;if(!Array.isArray(v)||!v.length||new Set(v).size!==v.length||v.some(x=>!ref.has(x)))bad('参照先または個数が不正');}
 if(op.entity==='skills'){
  const ranges={power:[0,5],cost:[0,999],hits:[1,8],statusChance:[0,1],healRate:[0,1],duration:[1,10],selfHeal:[0,1],guard:[0,.8],partyGuard:[0,.8],evasion:[0,.5],crit:[0,.5],splash:[0,3],drain:[0,.5],cleanseChance:[0,1],partyHeal:[0,1],mpHeal:[0,.3],selfGuard:[0,.8],lowHpScale:[0,1]};if(ranges[f]&&(typeof v!=='number'||!Number.isFinite(v)||v<ranges[f][0]||v>ranges[f][1]||['cost','hits','duration'].includes(f)&&!Number.isInteger(v)))bad('数値範囲が不正');
  if(f==='type'&&!['physical','magic'].includes(v)||f==='target'&&!['single','all','self'].includes(v)||f==='side'&&!['enemy','ally'].includes(v))bad('値が不正');
  if(f==='status'&&!['','poison','burn','paralyze','sleep','stun','confuse'].includes(v))bad('状態が不正');
  if(['heal','selfCleanse','ignoreEvasion'].includes(f)&&typeof v!=='boolean')bad('true/falseを指定');
  if(['buff','debuff','selfBuff','partyBuff'].includes(f)&&(!v||typeof v!=='object'||Array.isArray(v)||Object.entries(v).some(([k,n])=>!['atk','def','mag','mnd','spd'].includes(k)||typeof n!=='number'||!Number.isFinite(n)||Math.abs(n)>.5)))bad('能力補正が不正');
  if(f==='customEffect'&&v)bad('独自効果は要実装。説明を入力するだけでは動作しません');if(f==='description')warnings.push(item.name+': 説明のみの変更は効果を変更しません');
 }
 if(op.entity==='recordFusions'&&f==='condition'&&v!==item.value.condition)bad('レコード融合条件の変更は要実装');
 if(['requiredLineage','grantLineage'].includes(f)&&v!==item.value[f])bad('系譜の変更は要実装');
 if(f==='milestones'&&Array.isArray(v)){const known=new Set(d.records.flatMap(r=>r.milestones.filter(m=>m.type!=='SKILL').map(m=>m.type+'|'+m.reward)));if(v.some(m=>m.type!=='SKILL'&&!known.has(m.type+'|'+m.reward)))bad('新しい能力報酬の文章は要実装。既存報酬を選んでください');}
 if(f==='milestones'&&(!Array.isArray(v)||v.length!==10||v.some(m=>!Number.isInteger(m.level)||m.level<1||m.level>70||!['STAT','SKILL','PASSIVE'].includes(m.type)||typeof m.reward!=='string'||!m.reward.trim()||m.type==='SKILL'&&!d.skills[m.reward])||new Set(v.map(m=>m.level)).size!==10))bad('10段階と有効な習得技を指定');
 if(op.entity==='fusions'&&['a','b','result'].includes(f)&&!names.has(v))bad('実在するモンスター名を指定');if(op.entity==='recordFusions'&&['a','b','result'].includes(f)&&!records.has(v))bad('実在するレコード名を指定');
 if(op.entity==='fusions'&&f==='condition'&&!/^(追加条件なし|両SOUL特性Lv(?:[1-9]|[1-6][0-9]|70)以上)$/.test(v))bad('対応条件は追加条件なし／両SOUL特性Lv1～70以上');
 if(op.entity==='passives')warnings.push(item.name+': パッシブ説明の編集は実装効果を変更しません');
 item.value[f]=copy(v);
 }
 for(const row of tables.monsters){const m=row.value,n=m.rank==='MOB'?3:['A','S','SS'].includes(m.rank)?2:1;if(m.passives.length!==n)errors.push(m.name+': ランクに対応するパッシブ枠数は'+n);}
 for(const row of tables.skills){const s=row.value;if(s.power===0&&!s.heal&&!s.revive&&!s.buff&&!s.guard&&!s.status&&!s.selfBuff&&!s.partyBuff)errors.push(s.name+': 実行できる効果がありません');}
 for(const op of patch.ops)if(op.entity==='skills'&&!['description','customEffect'].includes(op.field)){const row=tables.skills.find(x=>x.id===op.id);if(row&&!patch.ops.some(p=>p.entity==='skills'&&p.id===op.id&&p.field==='description'))row.value.description=window.MOBMON_COMPANION.describe(row.value);}
 return{errors,warnings,data:errors.length?null:clone};}
window.MOBMON_PATCH={fields,entities,validate,copy};
})();
