const fs=require('fs'),assert=require('assert/strict'),{chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.stack));page.setDefaultTimeout(15000);await page.route('**/js/game.js*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('js/game.js','utf8').replace('renderBattle();runBattle();','renderBattle();').replace(/applyTestV6\(\);\r?\nrender\(\);/,'window.T={state:()=>state,battle:()=>battle,startBattle,renderBattle,playerTurn,dealDamage,counterDamage,endActorTurn,enemyDefeatV30,finishBattle,endBattleToScreen,chooseTarget,refillEnemyFront,playSkillEffect,skillDef};applyTestV6();render();')}));await page.goto('http://127.0.0.1:4173');await page.locator('#seedBtn').click();await page.waitForTimeout(1900);
const start=async(names=['モブスライム','モブロック','モブバード'],extra={})=>{await page.evaluate(({names,extra})=>{if(T.battle())T.endBattleToScreen(true,false);T.startBattle({mode:'exploration',area:'草原',useFullParty:true,title:'戦闘レイアウト確認',enemyRoster:names.map(name=>({name,level:25})),...extra});const b=T.battle();b.activeActor=b.allies[0];window.turnDone=T.playerTurn(b.activeActor);},{names,extra});await page.waitForTimeout(1900)};
await start();for(const [width,height] of [[320,568],[375,667],[390,844],[430,932]]){await page.setViewportSize({width,height});await page.waitForTimeout(150);assert.equal(await page.locator('.ally-stage-v5,.super-stage-v29,.battle-roster-v29').count(),0);assert.equal(await page.locator('.main-card-v30').count(),4);assert.equal(await page.locator('.super-card-v30').count(),2);const layout=await page.evaluate(()=>{const roster=document.querySelector('.battle-roster-v30').getBoundingClientRect(),commands=document.querySelector('.battle-command-v3').getBoundingClientRect(),enemy=document.querySelector('.enemy-stage-v3').getBoundingClientRect();return {top:roster.top,bottom:roster.bottom,commands:commands.top,enemyBottom:enemy.bottom,width:document.documentElement.scrollWidth,squares:[...document.querySelectorAll('.portrait-art-v30')].map(e=>{const r=e.getBoundingClientRect();return Math.abs(r.width-r.height)})};});await page.screenshot({path:`tests/screenshots/030-layout-${width}.png`});assert(layout.bottom<=layout.commands+1,JSON.stringify(layout));assert(layout.top>=height*.38,JSON.stringify(layout));assert(layout.enemyBottom<=layout.top+2,JSON.stringify(layout));assert(layout.width<=width);assert(layout.squares.every(x=>x<1),JSON.stringify(layout));}
await page.setViewportSize({width:390,height:844});await page.locator('.super-card-v30').first().click();assert(await page.locator('.battle-inspect-v29').isVisible());await page.locator('#battleInspectBack').click();await page.evaluate(()=>{window.healTarget=T.chooseTarget('ally');});const healUid=await page.locator('.main-card-v30').nth(2).getAttribute('data-combat-uid');await page.locator('.main-card-v30').nth(2).click();assert.equal(await page.evaluate(async()=>(await healTarget).uid),healUid);
// A lethal hit stays on screen through its effect; it is registered once only.
await page.locator('[data-battle-enemy]').nth(1).click();const deadUid=await page.locator('[data-battle-enemy]').nth(1).getAttribute('data-combat-uid');await page.evaluate(()=>{T.battle().enemies[1].hp=1;});await page.locator('[data-cmd=attack]').click();await page.locator('.defeating-v30').waitFor();assert.equal(await page.locator('.defeating-v30').getAttribute('data-combat-uid'),deadUid);assert(await page.locator('.defeating-v30').isDisabled());await page.waitForTimeout(160);await page.screenshot({path:'tests/screenshots/030-defeat.png'});await page.evaluate(()=>turnDone);assert.equal(await page.locator(`[data-combat-uid="${deadUid}"]`).count(),0);assert.equal(await page.evaluate(()=>T.battle().defeated.length),1);await page.evaluate(()=>T.enemyDefeatV30(T.battle().enemies[1]));assert.equal(await page.evaluate(()=>T.battle().defeated.length),1);assert.notEqual(await page.evaluate(()=>T.battle().selectedEnemyUid),deadUid);
// Counter and status damage use the same death handling, including their rewards.
await page.evaluate(()=>{const b=T.battle(),t=b.enemies[0];t.hp=1;window.counterDone=T.counterDamage(b.allies[0],t,false);});await page.locator('.defeating-v30').waitFor();await page.evaluate(()=>counterDone);assert.equal(await page.evaluate(()=>T.battle().defeated.length),2);
await page.evaluate(()=>{const e=T.battle().enemies[2];e.hp=1;e.status.poison=1;window.statusDone=T.endActorTurn(e);});await page.locator('.defeating-v30').waitFor();await page.evaluate(()=>statusDone);assert.equal(await page.evaluate(()=>T.battle().defeated.length),3);await page.evaluate(()=>T.finishBattle(true));assert(await page.locator('.battle-result-v4').isVisible());await page.locator('#battleResultNext').click();
await start(['モブホーク'],{encounterKind:'boss'});await page.evaluate(()=>{const b=T.battle();b.enemies[0].hp=1;window.bossDone=T.dealDamage(b.allies[0],b.enemies[0],{name:'攻撃',type:'physical',element:'無',power:2});});await page.locator('.defeating-v30').waitFor();await page.waitForTimeout(180);await page.screenshot({path:'tests/screenshots/030-boss-defeat.png'});await page.evaluate(()=>bossDone);assert.equal(await page.evaluate(()=>T.battle().defeated.length),1);
await start(['モブスライム','モブロック','モブバード','モブスライム','モブロック'],{mode:'arena'});await page.evaluate(()=>{const b=T.battle();b.enemies[0].hp=1;window.reserveKill=T.dealDamage(b.allies[0],b.enemies[0],{type:'physical',element:'無',power:2});});await page.evaluate(()=>reserveKill);await page.evaluate(()=>{T.refillEnemyFront();T.renderBattle()});assert.equal(await page.locator('[data-battle-enemy]').count(),4);assert.equal(await page.evaluate(()=>T.battle().enemies[4].slot),0);
await start(['モブスライム']);await page.evaluate(()=>{const b=T.battle();T.state().settings.battleSpeed=5;b.enemies[0].hp=1;b.enemies[0].status.burn=1;window.burnDone=T.endActorTurn(b.enemies[0]);});await page.evaluate(()=>burnDone);assert.equal(await page.evaluate(()=>T.battle().enemies[0].defeatDuration),240);assert.equal(await page.evaluate(()=>T.battle().defeated.length),1);await page.evaluate(()=>T.state().settings.battleSpeed=1);
await start();await page.evaluate(()=>{window.areaFx=T.playSkillEffect({name:'レインボー1990',target:'all'},null,'enemy');});await page.locator('.skill-fx-912').waitFor();const centered=await page.evaluate(()=>{const fx=document.querySelector('.skill-fx-912').getBoundingClientRect(),host=document.querySelector('.main-cards-v30').getBoundingClientRect();return Math.abs(fx.x+fx.width/2-host.x-host.width/2)<2;});assert(centered);await page.evaluate(()=>areaFx);
await page.emulateMedia({reducedMotion:'reduce'});await start(['モブスライム']);await page.evaluate(()=>{const b=T.battle();b.enemies[0].hp=1;window.reducedDone=T.dealDamage(b.allies[0],b.enemies[0],{type:'physical',element:'無',power:2});});await page.evaluate(()=>reducedDone);assert.equal(await page.evaluate(()=>T.battle().enemies[0].defeatDuration),180);assert.equal(await page.locator('.defeating-v30').count(),0);
assert.deepEqual(errors,[]);fs.writeFileSync('tests/battle-v0030-results.json',JSON.stringify({passed:true,checks:['4 responsive square portrait layouts','main and super detail, ally targeting','sticky enemy selection and lethal attack','counter and poison defeats','unique defeat/reward registration','boss death, reserve entry, reduced motion'],errors},null,2));console.log('v0030 battle browser OK');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
