const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const root=path.resolve(__dirname,'..'),base='http://127.0.0.1:4189/';
const expose='window.T={state:()=>state,battle:()=>battle,createInstance,save,ui:()=>ui,go,assignV6,openRecordView,closeModal,startBattle,executeSkillV257,endBattleToScreen,renderBattle,dealDamage,learnedSkills,recordBonuses,gainRecordExp,nextRecordExp,soulToken,addSoul,fusionCandidates,birthV6};';
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',async r=>{const u=new URL(r.request().url());if(u.origin!==new URL(base).origin)return r.abort();const rel=decodeURIComponent(u.pathname).replace(/^\//,'')||'index.html';for(const parent of [root,'D:/GitHub/MOB-MONSTERS']){const file=path.join(parent,rel);if(!fs.existsSync(file)||!fs.statSync(file).isFile())continue;let body=fs.readFileSync(file);if(rel==='js/game.js'){body=body.toString().replace('let titleActive=true;','let titleActive=false;').replace('renderBattle();runBattle();','renderBattle();').replace(/applyTestV6\(\);\r?\nrender\(\);/,expose+'applyTestV6();render();');}return r.fulfill({body,contentType:rel.endsWith('.js')?'text/javascript':rel.endsWith('.html')?'text/html':rel.endsWith('.css')?'text/css':rel.endsWith('.png')?'image/png':'application/octet-stream'});}return r.abort();});
await page.addInitScript(()=>localStorage.setItem('mob_monsters_core_v001',JSON.stringify({version:1,owned:[{uid:'old-uid',name:'モブホーク',level:47,exp:123,cassette:9,records:[{name:'モブホーク',level:70,exp:0}],activeRecord:'モブホーク',lineage:['OLD']}],party:['old-uid'],souls:{},flags:{demoSeeded:true},seen:{},settings:{battleSpeed:3},gold:9876})));
await page.goto(base);await page.waitForFunction(()=>window.T);assert.equal(await page.evaluate(()=>T.state().owned[0].level),47);
await page.evaluate(()=>{const s=T.state();for(let i=1;i<10;i++)s.owned.push(T.createInstance(MOBMON_DATA.monsters[i].name,30,false));s.party=s.owned.slice(0,8).map(x=>x.uid);T.go('party');});
const owned=await page.evaluate(()=>T.state().owned.map(x=>x.uid));await page.locator(`[data-owned="${owned[8]}"]`).click();await page.locator('[data-slot="0"]').click();assert.equal(await page.evaluate(()=>T.state().party[0]),owned[8]);assert(await page.evaluate(id=>T.state().owned.some(x=>x.uid===id),owned[0]));
await page.locator('[data-slot="0"]').click();await page.locator('[data-slot="1"]').click();assert.deepEqual(await page.evaluate(()=>T.state().party.slice(0,2)),[owned[1],owned[8]]);
await page.locator('[data-slot="0"]').click();await page.locator('[data-slot="0"]').click();assert.equal(await page.evaluate(()=>T.state().party[0]),owned[1]);await page.locator(`[data-owned="${owned[1]}"]`).click();await page.locator('#partyRemove').click();assert.equal(await page.evaluate(()=>T.state().party[0]),null);
await page.evaluate(id=>T.assignV6(id),owned[9]);assert.equal(await page.locator('#partyHint').textContent(),(await page.evaluate(()=>T.state().owned[9].name))+'：配置先を選んでください');await page.locator('[data-slot="0"]').click();await page.locator(`[data-owned="${owned[0]}"]`).click();await page.locator('#partyCancel').click();assert.equal(await page.evaluate(()=>T.ui().selectedUid),null);
await page.locator(`[data-owned="${owned[0]}"]`).click();await page.locator('[data-slot="0"]').dblclick();assert.equal(await page.evaluate(()=>new Set(T.state().party.filter(Boolean)).size),8);await page.screenshot({path:path.join(__dirname,'companion-party-390.png'),fullPage:true});for(const width of [320,375]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await page.setViewportSize({width:390,height:844});
await page.evaluate(()=>T.openRecordView('火の音'));await page.locator('[data-record-skill]').first().click();assert(await page.locator('#backToRecord').isVisible());await page.screenshot({path:path.join(__dirname,'companion-skill-detail.png')});await page.locator('#backToRecord').click();await page.evaluate(()=>T.closeModal());
const combat=await page.evaluate(async()=>{T.startBattle({enemyRoster:[{name:'モブスライム',level:30},{name:'モブホーク',level:30}],useFullParty:true});const b=T.battle();b.round=1;const a=b.enemies[0],targets=b.allies;for(const t of targets){t.hp=t.maxHp=10000;t.m={...t.m,passives:[]};}a.m={...a.m,passives:[]};a.atk=a.mag=100;a.hp=a.maxHp=10000;b.activeActor=a;const animations=[],originalAnimate=Element.prototype.animate;Element.prototype.animate=function(...args){if(this.dataset.combatUid){const canvas=[...document.querySelectorAll('.companion-sprite')].find(c=>c.dataset.target===this.dataset.combatUid);animations.push({uid:this.dataset.combatUid,frame:canvas?.dataset.frame});}return originalAnimate.apply(this,args)};const before=targets.map(t=>t.hp);await T.executeSkillV257(a,{...MOBMON_DATA.skills['フレイムマジック'],status:null});const changes=targets.map((t,i)=>before[i]-t.hp);const healer=b.allies[0],target=b.allies[1];target.hp=1;const hp=target.hp;await T.executeSkillV257(healer,MOBMON_DATA.skills['マカロン・ティータイム'],target);const healed=target.hp-hp;const first=healed;target.hp=1;await T.executeSkillV257(healer,MOBMON_DATA.skills['マカロン・ティータイム'],target);const repeat=target.hp>1;Element.prototype.animate=originalAnimate;return {animations,changes,healed,repeat,fields:JSON.stringify(b).includes('skillReadyAt')};});assert.equal(combat.changes.length,8);assert(combat.changes.every(n=>n>0));assert.equal(combat.animations.length,8);assert(combat.animations.every(x=>x.frame==='2'));assert(combat.healed>=2500);assert(combat.repeat);assert.equal(combat.fields,false);
await page.evaluate(()=>(T.endBattleToScreen(true,false),T.go('party')));await page.waitForTimeout(400);assert.equal(await page.locator('.companion-fx-layer').count(),0);assert.equal(await page.locator('[data-slot]').count(),8);
const fx=await page.evaluate(async()=>{let draws=[];const draw=CanvasRenderingContext2D.prototype.drawImage;CanvasRenderingContext2D.prototype.drawImage=function(...a){draws.push(a.slice(1,5));return draw.apply(this,a)};const host=document.createElement('div');host.style.cssText='position:fixed;inset:0';document.body.append(host);await MOBMON_COMPANION_FX.play(MOBMON_DATA.skills['フレイムマジック'],[{uid:'missing'}],host,()=>true,1);const atImpact=document.querySelector('.companion-sprite').dataset.frame;await new Promise(r=>setTimeout(r,350));host.remove();CanvasRenderingContext2D.prototype.drawImage=draw;return {draws,atImpact};});assert.equal(fx.atImpact,'2');assert.equal(fx.draws.length,4);assert.equal(fx.draws[0].length,4);assert.notDeepEqual(fx.draws[0],fx.draws[1]);
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'companion-browser-results.json'),JSON.stringify({passed:true,combat,fx,errors,checks:['legacy save','reserve placement','swap','same slot','removal','cancel','double click uniqueness','320/375/390 width','record skill detail','enemy all targets damaged','tea repeat no cooldown','battle end clears FX','manifest 4 frames at impact 2']},null,2));console.log('PASS companion browser');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});

