const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require('C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.join(__dirname,'screenshots/v041');fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[],results=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);
await p.route('**/js/game.js*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(root,'js/game.js'),'utf8').replace('let titleActive=true;','let titleActive=false;').replace(/applyTestV6\(\);\r?\nrender\(\);/,'window.T={state:()=>state,ui,go,render,seedDemo,addSoul,fusionV6,birthV6,createInstance,drawRosterV6,save,load,fusionCandidates,exploration,monsterStats,withSelectedSoulsV6};applyTestV6();render();')}));
await p.goto('http://127.0.0.1:4173');await p.waitForFunction(()=>window.T);await p.evaluate(()=>{T.seedDemo();T.go('home')});await p.waitForTimeout(500);
for(const width of [320,360,390,430]){await p.setViewportSize({width,height:844});for(const screen of ['home','room','fusion','party','story']){await p.evaluate(s=>T.go(s),screen);await p.waitForTimeout(100);const layout=await p.evaluate(()=>({page:document.documentElement.scrollWidth,screen:document.querySelector('#screen').scrollWidth,client:document.querySelector('#screen').clientWidth,broken:[...document.querySelectorAll('#screen img')].filter(i=>i.complete&&!i.naturalWidth).map(i=>i.src)}));assert(layout.page<=width,screen+' page overflow '+width);assert(layout.screen<=layout.client+1,screen+' screen overflow '+width+JSON.stringify(layout));assert.equal(layout.broken.length,0,screen+' broken image');await p.screenshot({path:path.join(out,`v041-${screen}-${width}.png`)});results.push({screen,width,layout});}}
await p.setViewportSize({width:390,height:844});
// Old save, private decoration settings and only actually acquired stickers.
await p.evaluate(()=>{delete T.state().roomDecor;T.state().stickers={};T.go('room')});assert.equal(await p.locator('#roomSticker option').count(),1);await p.locator('[data-room-light=dusk]').click();assert.equal(await p.evaluate(()=>T.load().roomDecor.light),'dusk');await p.evaluate(()=>{T.state().stickers[T.state().owned[0].name]=1;T.go('room')});assert.equal(await p.locator('#roomSticker option').count(),2);await p.locator('#roomSticker').selectOption({index:1});assert.equal(await p.locator('.journey-keepsake').count(),1);
// Filters survive roster redraw and do not change party rules or members.
await p.evaluate(()=>T.go('party'));const before=await p.evaluate(()=>T.state().party.slice());await p.locator('#journeySearch').fill('存在しない仲間');assert.equal(await p.locator('#rosterV6 [data-owned]:visible').count(),0);await p.locator('#journeySearch').fill('');await p.locator('[data-owned]').last().click();await p.locator('[data-slot="0"]').click();const after=await p.evaluate(()=>T.state().party.slice());assert.equal(after.length,8);assert.equal(new Set(after.filter(Boolean)).size,after.filter(Boolean).length);assert.notEqual(before[0],after[0]);
// Progression graph includes each campaign entry and respects original unlock decisions.
await p.evaluate(()=>T.go('story'));assert.equal(await p.locator('[data-map-entry]').count(),await p.evaluate(()=>MOBMON_CAMPAIGN.entries.length));const original=await p.locator('.journey-map-world').getAttribute('style');await p.locator('#mapZoomIn').click();assert.notEqual(await p.locator('.journey-map-world').getAttribute('style'),original);await p.locator('#mapCurrent').click();
const rect=await p.locator('.journey-map-window').boundingBox();await p.mouse.move(rect.x+rect.width*.5,rect.y+180);await p.mouse.down();await p.mouse.move(rect.x+rect.width*.5+80,rect.y+80,{steps:8});await p.mouse.up();assert.equal(await p.locator('#modal:visible').count(),0);
await p.locator('#mapCurrent').click();await p.locator('#journeyDepart').click();await p.locator('#answerNo').click();assert.equal(await p.evaluate(()=>!!T.exploration.active()),false);
// Fusion commits once, skipping changes only the presentation, and reload recovers the result.
await p.evaluate(()=>{T.go('fusion');const s=T.state(),souls=Object.values(s.souls).flat();T.ui.fusion=[souls[0],souls[1]];T.fusionV6(document.querySelector('#screen'))});
const count=await p.evaluate(()=>({owned:T.state().owned.length,souls:Object.values(T.state().souls).flat().length}));
await p.evaluate(()=>{const[a,b]=T.ui.fusion,c=T.withSelectedSoulsV6(()=>T.fusionCandidates(a.name,b.name))[0];window.birthDone=T.birthV6(c,[]);void T.birthV6(c,[])});await p.locator('#journeySkip').click();await p.evaluate(()=>birthDone);assert.equal(await p.evaluate(()=>T.state().owned.length),count.owned+1);assert.equal(await p.evaluate(()=>Object.values(T.state().souls).flat().length),count.souls-2);assert.equal(await p.evaluate(()=>T.load().owned.length),count.owned+1);await p.screenshot({path:path.join(out,'v041-birth-result.png')});await p.locator('#birthNo').click();
await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>T.go('home'));assert.equal(await p.locator('.journey-companions .stage-art-v3').first().evaluate(e=>getComputedStyle(e).animationName),'none');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'v041-results.json'),JSON.stringify({passed:true,results,checks:['4 mobile widths, five screens, no horizontal overflow or broken images','old-save decoration defaults and persisted acquired stickers only','party search and eight-slot swap with unique members','campaign-derived map graph and cancel departure','drag does not trigger departure','fusion duplicate call and skip consume exactly two souls and save one child','reduced motion'],errors},null,2));console.log('v041 checks passed');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
