const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert/strict'),fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});const errors=[];try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');await page.locator('#seedBtn').click();await page.locator('#assetLoading').waitFor({state:'hidden'});const base=await page.evaluate(()=>JSON.parse(localStorage.getItem('mob_monsters_core_v001')));
 for(const [w,h]of [[390,844],[320,568]]){const s=structuredClone(base);s.screen='party';s.party[0]=null;await page.evaluate(s=>localStorage.setItem('mob_monsters_core_v001',JSON.stringify(s)),s);await page.setViewportSize({width:w,height:h});await page.reload();await page.locator(`[data-owned="${s.owned[0].uid}"]`).click();await page.locator('#assetLoading').waitFor({state:'hidden'});await page.locator('#modalBody').evaluate(e=>e.scrollTop=e.scrollHeight);const rect=await page.locator('#toSoulBtn').boundingBox(),card=await page.locator('.modal-card').boundingBox(),body=await page.locator('#modalBody').boundingBox();assert(card.y>=12);assert(card.y+card.height<=h-27);assert(rect.y>=body.y);assert(rect.y+rect.height<=body.y+body.height);assert(rect.height>=50);await page.screenshot({path:`tests/screenshots/24-popup-${w}.png`});await page.locator('#toSoulBtn').click();assert.equal(await page.locator('#answerYes').count(),1);await page.locator('#answerNo').click();}
 // Cold start under intentionally slow images. Release UI before the images finish.
 const slow=await browser.newPage({viewport:{width:390,height:844}});slow.on('pageerror',e=>errors.push(e.message));await slow.addInitScript(s=>localStorage.setItem('mob_monsters_core_v001',JSON.stringify(s)),base);await slow.route('**/*.png',async route=>{await new Promise(r=>setTimeout(r,5200));await route.continue().catch(()=>{});});
 const began=Date.now();await slow.goto('http://127.0.0.1:4173',{waitUntil:'domcontentloaded'});await slow.locator('#assetLoading').waitFor({state:'visible'});assert(Number(await slow.locator('#loadingProgress').getAttribute('max'))<=25);await slow.screenshot({path:'tests/screenshots/24-loading.png'});await slow.locator('#assetLoading').waitFor({state:'hidden',timeout:4600});const elapsed=Date.now()-began;assert(elapsed<4600);assert.equal(await slow.locator('#app').evaluate(e=>e.inert),false);await slow.waitForFunction(()=>[...document.querySelectorAll('.company-member img')].every(i=>i.complete&&i.naturalWidth>0),{},{timeout:15000});assert.equal(await slow.locator('.company-member .asset-waiting').count(),0);
 // Cached HOME does not re-open a loading screen.
 await slow.unroute('**/*.png');await slow.locator('.bottom-nav [data-go=party]').click();await slow.locator('.bottom-nav [data-go=home]').click();await slow.waitForTimeout(250);assert(await slow.locator('#assetLoading').isHidden());
 const offline=await browser.newPage();offline.on('pageerror',e=>errors.push(e.message));await offline.addInitScript(s=>localStorage.setItem('mob_monsters_core_v001',JSON.stringify(s)),base);await offline.route('**/*.png',route=>route.abort());await offline.goto('http://127.0.0.1:4173',{waitUntil:'domcontentloaded'});await offline.waitForTimeout(3800);assert(await offline.locator('#assetLoading').isHidden());assert.equal(await offline.locator('#app').evaluate(e=>e.inert),false);await offline.locator('.bottom-nav [data-go=settings]').click();assert.equal(await offline.locator('.setting-toggle').count(),7);
 assert.deepEqual(errors,[]);fs.writeFileSync('tests/loading-results.json',JSON.stringify({result:'PASS',popupWidths:[320,390],slowInitialReleaseMs:elapsed,checks:['popupAboveBottom','lastButtonVisibleAndClickable','coldLoadDeadline','lateImagesAppear','cachedNoOverlay','offlineNoLock'],errors},null,2));console.log('Loading / modal PASS',elapsed+'ms cold upper-bound release');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
