const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{
 fs.mkdirSync('tests/screenshots',{recursive:true});const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('mob_monsters_core_v001')));
 const snap=async name=>{await page.waitForTimeout(180);await page.screenshot({path:`tests/screenshots/${name}.png`});};
 const home=async()=>{await page.locator('.bottom-nav [data-go=home]').click();await page.locator('#screen').evaluate(e=>e.scrollTop=0);};
 const yes=()=>page.locator('#answerYes').click();const no=()=>page.locator('#answerNo').click();
 const fixture=async s=>{await page.evaluate(s=>localStorage.setItem('mob_monsters_core_v001',JSON.stringify(s)),s);await page.reload();};
 const noOverflow=async()=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('#screen').evaluate(e=>e.scrollWidth<=e.clientWidth));};
 await page.goto('http://127.0.0.1:4173');await page.locator('#seedBtn').click();await page.waitForTimeout(1600);
 assert.equal(await page.locator('[data-home-mon]').count(),10);await noOverflow();await snap('01-home');let base=await saved();
 console.log('HOME: 10 members / 4+2+4 / images loaded',await page.locator('.company-member img').evaluateAll(a=>a.filter(i=>i.complete&&i.naturalWidth>0).length));
 await page.locator('.facility.castle').click();await page.waitForTimeout(500);await snap('02-castle');assert(await page.locator('.speech').innerText());await home();
 await page.locator('.facility.shop').click();const goldBefore=(await saved()).gold;await page.locator('[data-shop="0"]').click();await no();assert.equal((await saved()).gold,goldBefore);await page.locator('[data-shop="0"]').click();await yes();assert.equal((await saved()).gold,goldBefore-200);await snap('03-shop');await home();
 await page.locator('.facility.gacha').click();await page.locator('#drawSticker').click();await yes();assert.equal(Object.values((await saved()).stickers).reduce((a,b)=>a+b,0),1);await page.locator('#modalClose').click();await snap('04-gacha');await home();
 await page.locator('.facility.story').click();await noOverflow();await snap('05-adventure');await home();await page.locator('.company-status [data-go=arena]').click();await snap('06-arena');await home();
 // Large roster: keep exactly the same scroll position and sort on assigning.
 const large=await saved();large.screen='party';for(let i=0;i<85;i++){const inst=JSON.parse(JSON.stringify(large.owned[i%10]));inst.uid='fixture_'+i;inst.level=1+i%30;large.owned.push(inst);}large.soulPoints=5000;await fixture(large);
 assert.equal(await page.locator('[data-slot]').count(),10);await snap('07-party-top');
 const original=(await saved()).party;await page.locator('[data-slot="0"]').click();await page.locator('[data-slot="4"]').click();assert.equal((await saved()).party[4],original[0]);
 await page.locator('#partySort').selectOption('rank');await page.locator('#screen').evaluate(e=>e.scrollTop=e.scrollHeight);await page.locator('[data-owned]').last().click();const scroll=await page.locator('#screen').evaluate(e=>e.scrollTop);await snap('08-detail');await page.locator('#addParty').click();await page.locator('[data-dest="2"]').click();await yes();assert.equal(await page.locator('#screen').evaluate(e=>e.scrollTop),scroll);assert.equal(await page.locator('#partySort').inputValue(),'rank');await snap('09-party-scroll-kept');
 await page.locator('[data-owned]').last().click();await page.locator('#trainRecord').click();await page.locator('#levelPlus').click();await snap('10-record-training');let before=await saved();await page.locator('#levelExecute').click();await no();assert.deepEqual((await saved()).owned,before.owned);await page.locator('#levelExecute').click();await yes();assert((await saved()).soulPoints<before.soulPoints);await snap('11-level-up');await page.locator('#modalClose').click();await home();
 console.log('PARTY: swap, 95-member roster, sort retained, scroll unchanged; RECORD: cancel and 2-level growth passed');
 await page.locator('.bottom-nav [data-go=settings]').click();const normal=await saved();await page.locator('[data-setting=testMode]').click();await yes();
 for(const key of ['fastBattle','itemsMax','goldMax','diamondsMax','soulsMax','pointsMax']){await page.locator(`[data-setting=${key}]`).click();await yes();}
 const maxed=await saved();assert.equal(maxed.settings.battleSpeed,5);assert.equal(maxed.gold,9999999);assert.equal(maxed.diamonds,9999999);assert.equal(maxed.soulPoints,9999999);assert(Object.values(maxed.souls).every(a=>a.length>=10));await snap('12-settings');await page.reload();assert.equal((await saved()).settings.pointsMax,true);await page.locator('[data-setting=testMode]').click();const restored=await saved();assert.equal(restored.gold,normal.gold);assert.equal(restored.soulPoints,normal.soulPoints);assert.equal(restored.settings.battleSpeed,1);assert.equal(Object.values(restored.souls).flat().length,Object.values(normal.souls).flat().length);
 console.log('SETTINGS: seven switches, persistence, master OFF restores balances passed');
 await fixture({...base,screen:'soul'});await page.locator('#lilithMenu').click();assert(!await page.locator('.lab-menu').innerText().then(t=>t.includes('レコード')));await page.locator('#openSoulBank').click();await page.locator('#soulSort').selectOption('attribute');await page.locator('[data-soul-index]').first().click();await snap('13-soul-info');await page.locator('#soulInfoBack').click();await page.locator('#soulBack').click();await snap('14-lab');await page.locator('#lilithMenu').click();await page.locator('#openSoulFusion').click();
 const choose=async(slot,name)=>{await page.locator(`[data-fusion-slot="${slot}"]`).click();await page.locator('.soul-tile').filter({hasText:name}).first().click();await yes();};
 await choose(0,'モブフレイム');await choose(1,'モブブリザード');await page.locator('#answerCancel').click();assert.equal((await saved()).owned.length,10);assert.equal(await page.locator('.source-plus').count(),2);
 await choose(0,'モブフレイム');await choose(1,'モブブリザード');await yes();assert.equal(await page.locator('.candidate-v6 b').first().innerText(),'???');assert.equal(await page.locator('.candidate-v6 img').first().getAttribute('alt'),'???');await snap('15-fusion-candidates');await page.locator('[data-candidate]').first().click();await yes();assert.equal((await saved()).owned.length,10);const started=Date.now();await page.locator('#birthDecide').click();await page.waitForTimeout(1100);await snap('16-fusion-light');assert.equal((await saved()).owned.length,11);assert.equal(await page.locator('#birthYes').count(),0);await page.locator('#birthYes').waitFor({timeout:6500});assert(Date.now()-started>=3800);await snap('17-birth');const born=await saved();assert.equal(born.souls['モブフレイム'].length,1);assert.equal(born.souls['モブブリザード'].length,1);assert.equal(born.owned.at(-1).name,'モブフレザード');assert.equal(born.owned.at(-1).level,1);await page.locator('#birthYes').click();assert((await page.locator('#screen').getAttribute('class')).includes('party-v6'));await page.locator('#modalClose').click();
 console.log('FUSION: clear, unknown silhouette, confirmation, two souls consumed, 3-second light, Lv1 birth, party route passed');
 for(const [width,height] of [[320,568],[390,844],[430,932]]){await page.setViewportSize({width,height});await home();await noOverflow();await snap(`18-home-${width}`);await page.locator('.bottom-nav [data-go=party]').click();await page.locator('#screen').evaluate(e=>e.scrollTop=0);await noOverflow();await snap(`19-party-${width}`);await page.locator('.bottom-nav [data-go=settings]').click();await noOverflow();}
 assert.deepEqual(errors,[]);fs.writeFileSync('tests/browser-results.json',JSON.stringify({result:'PASS',widths:[320,390,430],checks:['home10','facilities','shop','gacha','story','arena','partySwap','scrollRetained','sortRetained','recordNo','recordYes','sevenSwitches','switchRestore','fusionCancel','silhouette','soulConsumption','birthTiming','birthParty'],runtimeErrors:errors},null,2));console.log('ALL PRODUCTION BROWSER CHECKS PASSED');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
