const fs=require('fs'),assert=require('assert/strict');const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/js/game.js*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('js/game.js','utf8').replace('renderBattle();runBattle();','renderBattle();').replace(/applyTestV6\(\);\r?\nrender\(\);/,'window.T={state:()=>state,battle:()=>battle,beginOpening,createInstance,go,save,trainingV6,exploration,runBattle,endBattleToScreen,renderBattle};applyTestV6();render();')}));
await page.route('**/js/exploration.js*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('js/exploration.js','utf8').replace('active:()=>!!field','field:()=>field,generateCave,interact,active:()=>!!field')}));
await page.goto('http://127.0.0.1:4173');await page.locator('#seedBtn').click();await page.waitForTimeout(1050);await page.locator('#openingText').click();assert.equal(await page.locator('.opening-art').count(),0);assert((await page.locator('.dialogue-box small').innerText()).includes('ナレーション'));
// Check speech, tap-to-reveal, and system narration independently via saved checkpoints.
async function openingAt(index){await page.evaluate(index=>{T.state().opening.index=index;T.save()},index);await page.reload();await page.locator('#continueGame').click();}
await openingAt(18);assert(await page.locator('.opening-spoken').count());assert.equal(await page.locator('.opening-art .lilith-art').count(),1);const short=await page.locator('#openingText').innerText();await page.waitForTimeout(350);assert((await page.locator('#openingText').innerText()).length>short.length);await page.locator('#openingNext').click();assert.equal(await page.evaluate(()=>T.state().opening.index),18);assert.equal(await page.locator('#openingText').innerText(),'おや？目が覚めたかい？');await page.screenshot({path:'tests/screenshots/035-speech.png'});await page.locator('#openingNext').click();assert.equal(await page.evaluate(()=>T.state().opening.index),19);
await openingAt(43);await page.locator('#openingText').click();assert.equal(await page.locator('.lilith-art').count(),0);assert.equal(await page.locator('.dialogue-box small').innerText(),'ナレーション');await page.screenshot({path:'tests/screenshots/035-narration.png'});
for(let i=0;i<6&&await page.locator('#openingNext').count();i++){await page.locator('#openingText').click();await page.locator('#openingNext').click();}
assert.equal(await page.evaluate(()=>T.state().owned.length),1);
await page.evaluate(()=>{for(let i=0;i<3;i++)T.state().owned.push(T.createInstance('モブスライム',1));T.go('castle');});const gold=await page.evaluate(()=>T.state().gold);await page.locator('#lilithTalk').click();await page.locator('#dialogueText').click();assert((await page.locator('#dialogueText').innerText()).includes('素質'));await page.locator('#dialogueNext').click();await page.locator('#dialogueText').click();assert.equal(await page.locator('.dialogue-portrait').count(),0);assert.equal(await page.locator('.dialogue-box small').innerText(),'ナレーション');assert((await page.locator('#dialogueText').innerText()).includes('3000'));assert.equal(await page.evaluate(()=>T.state().gold),gold+3000);await page.locator('#modalClose').click();
await page.evaluate(()=>{const s=T.state();s.owned=s.owned.slice(0,1);s.party=[s.owned[0].uid];s.exploration={cleared:{}};s.settings.testMode=true;s.settings.battleSpeed=5;T.go('story')});await page.locator('[data-destination]').first().click();await page.locator('#normalDepth').click();await page.locator('#answerYes').click();await page.locator('.journey-overlay.depart.playing').waitFor();await page.screenshot({path:'tests/screenshots/035-depart.png'});await page.locator('.journey-overlay').waitFor({state:'detached'});assert.equal(await page.evaluate(()=>document.querySelector('#app').inert),false);assert(await page.evaluate(()=>T.exploration.field().entities.filter(e=>e.kind==='enemy').every(e=>e.level===3)));
await page.evaluate(()=>{const x=T.exploration;void x.interact(x.field().entities.find(e=>e.kind==='enemy'))});await page.waitForFunction(()=>!!T.battle());assert.equal(await page.evaluate(()=>T.battle().enemyRoster.length),1);assert.equal(await page.evaluate(()=>T.battle().enemyRoster[0].level),3);await page.evaluate(()=>{T.battle().autoBattle=true;void T.runBattle()});await page.locator('#battleResultNext').waitFor({timeout:30000});assert(await page.evaluate(()=>T.battle().result.win));await page.locator('#battleResultNext').click();
await page.evaluate(()=>{for(let i=0;i<2;i++){const a=T.createInstance('モブスライム',5);T.state().owned.push(a);T.state().party.push(a.uid);}const x=T.exploration,random=Math.random;Math.random=()=>.9;void x.interact(x.field().entities.find(e=>e.kind==='enemy'));Math.random=random;});await page.waitForFunction(()=>!!T.battle());assert.deepEqual(await page.evaluate(()=>T.battle().enemyRoster.map(e=>e.level)),[3,3]);await page.evaluate(()=>T.endBattleToScreen(false,true));
await page.locator('#leaveField').click();await page.locator('#answerYes').click();await page.locator('.journey-overlay.return.playing').waitFor();await page.screenshot({path:'tests/screenshots/035-return.png'});await page.locator('.journey-overlay').waitFor({state:'detached'});assert(await page.evaluate(()=>T.state().exploration.grassIntroComplete));assert.equal(await page.evaluate(()=>document.querySelector('#app').inert),false);
assert(await page.evaluate(()=>{const x=T.exploration;return !x.generate('草原',false,1).intro&&!x.generate('草原',false,2).intro&&!x.generateCave('草原',false,1).intro}));
await page.evaluate(()=>{T.state().soulPoints=999999;const a=T.state().owned[0];T.trainingV6(a.uid,a.records[0].name,15-a.records[0].level)});await page.locator('#levelExecute').click();await page.locator('#answerYes').click();await page.waitForTimeout(1500);assert(await page.locator('.level-new-skills b').count()>0);await page.screenshot({path:'tests/screenshots/035-level.png'});assert((await page.locator('.level-arrival').innerText()).includes('15'));
assert.deepEqual(errors,[]);console.log('035: typewriter, narrator identity, paged reward, depart/return, first grass Lv3 1–2 enemies, starter victory, assist completion and growth reveal OK');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
