const fs=require('fs'),assert=require('assert/strict');const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/js/game.js*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('js/game.js','utf8').replace('renderBattle();runBattle();','renderBattle();').replace(/applyTestV6\(\);\r?\nrender\(\);/,'window.T={state:()=>state,battle:()=>battle,go,save,createInstance,exploration,endBattleToScreen,awardBattleRewards};applyTestV6();render();')}));
await page.route('**/js/exploration.js*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('js/exploration.js','utf8').replace('active:()=>!!field','field:()=>field,interact,active:()=>!!field')}));
await page.goto('http://127.0.0.1:4173');await page.locator('#seedBtn').click();await page.evaluate(()=>{T.state().opening.index=14;T.save()});await page.reload();await page.locator('#continueGame').click();await page.locator('#openingText').click();assert.equal(await page.locator('#openingText').innerText(),'より良いソウルのモンスターを育成し');
await page.evaluate(()=>{T.state().opening.index=48;T.save()});await page.reload();await page.locator('#continueGame').click();await page.locator('#openingText').click();assert((await page.locator('#openingText').innerText()).includes('最初の冒険はソウルのドロップ率が少しだけ上がっています！'));assert.equal(await page.locator('.lilith-art').count(),0);await page.locator('#openingNext').click();
for(const [width,height]of [[390,844],[375,667],[320,568]]){await page.setViewportSize({width,height});for(const screen of ['soul','castle']){await page.evaluate(s=>T.go(s),screen);await page.waitForTimeout(1400);const selectors=screen==='soul'?['#labViewSouls','#labFusion','#labMonsterSoul','#labSoulRuby']:['#lilithTalk','#lilithHelp'];for(const selector of selectors){assert(await page.locator(selector).evaluate(e=>{const r=e.getBoundingClientRect(),nav=document.querySelector('.bottom-nav').getBoundingClientRect();return r.top>=78&&r.bottom<=nav.top&&r.width>=44&&r.height>=44&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('button')===e}),`${width}x${height} ${selector} clipped`);}assert.equal(await page.evaluate(()=>document.querySelector('#screen').scrollTop),0);await page.screenshot({path:`tests/screenshots/036-${screen}-${width}.png`});}}
await page.evaluate(()=>T.go('soul'));await page.locator('#labViewSouls').click();assert(await page.locator('#soulGrid').count());await page.evaluate(()=>T.go('soul'));await page.locator('#labFusion').click();assert(await page.locator('.fusion-sanctum').count());
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{const s=T.state();s.exploration={cleared:{},grassIntroComplete:true};s.settings.testMode=true;T.go('story')});await page.locator('[data-destination]').first().click();await page.locator('#normalDepth').click();await page.locator('#answerYes').click();await page.locator('.journey-overlay').waitFor({state:'detached'});assert(await page.evaluate(()=>T.exploration.field().intro));
async function encounter(){await page.evaluate(()=>{const x=T.exploration,random=Math.random;Math.random=()=>.99;void x.interact(x.field().entities.find(e=>e.kind==='enemy'));Math.random=random;});await page.waitForFunction(()=>!!T.battle());}
await encounter();assert.equal(await page.evaluate(()=>T.battle().enemyRoster.length),1);assert.equal(await page.evaluate(()=>T.battle().beginnerSoulBonus),.2);
const drops=await page.evaluate(()=>{const b=T.battle(),e=b.enemies[0],random=Math.random;e.hp=0;const rank=e.m.rank,base=MOBMON_DATA.rankDropRates[rank];Math.random=()=>base+.1;const boosted=T.awardBattleRewards().souls.length;b.beginnerSoulBonus=0;const ordinary=T.awardBattleRewards().souls.length;Math.random=random;return {boosted,ordinary}});assert.deepEqual(drops,{boosted:1,ordinary:0});
await page.evaluate(()=>{T.endBattleToScreen(false,true);const s=T.state(),a=T.createInstance('モブスライム',5);s.owned.push(a);s.party.push(a.uid)});await encounter();assert.equal(await page.evaluate(()=>T.battle().enemyRoster.length),1);
await page.evaluate(()=>{T.endBattleToScreen(false,true);const s=T.state(),a=T.createInstance('モブスライム',5);s.owned.push(a);s.party.push(a.uid);T.exploration.field().introWins=1});await encounter();assert.equal(await page.evaluate(()=>T.battle().enemyRoster.length),2);
assert.deepEqual(errors,[]);console.log('036: narration, phone facility button visibility and taps, persistent solo encounters for 1–2 main members, 3-member release, additive soul drops OK');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
