const fs=require('fs'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});const errors=[];
 try{
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});page.setDefaultTimeout(18000);page.on('pageerror',e=>errors.push(e.stack));
 await page.route('**/js/game.js*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('js/game.js','utf8').replace('renderBattle();runBattle();','renderBattle();').replace(/applyTestV6\(\);\r?\nrender\(\);/,'window.T={state:()=>state,battle:()=>battle,go,save,seedDemo,applyTestV6,createInstance,addSoul,soulBankV6,buildRuntimeEnemy,monsterStats,exploration,startBattle,endBattleToScreen};applyTestV6();render();')}));
 await page.route('**/js/exploration.js*',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('js/exploration.js','utf8').replace('active:()=>!!field','field:()=>field,generateCave,unlocked,interact,active:()=>!!field')}));
 await page.goto('http://127.0.0.1:4173');
 // Actual new game narrative; resume at name input to check save checkpoints.
 await page.locator('#seedBtn').click();assert(await page.locator('#openingNext').isDisabled());assert.equal(await page.locator('#openingSkip').count(),0);await page.waitForTimeout(1050);await page.locator('#openingNext').click();await page.locator('#openingText').click();
 assert((await page.locator('.opening-content').innerText()).includes('魔王が世界を支配'));
 await page.evaluate(()=>{T.state().opening.index=22;T.save();});await page.reload();await page.locator('#continueGame').click();await page.locator('#openingName').fill('テスト冒険者');await page.locator('#openingDecide').click();await page.locator('#openingText').click();assert((await page.locator('.opening-content').innerText()).includes('テスト冒険者'));await page.waitForTimeout(1300);await page.screenshot({path:'tests/screenshots/033-opening.png'});
 let noChecked=false;for(let i=0;i<35&&await page.locator('.opening-screen').count();i++){
  if(await page.locator('#openingName').count()){await page.locator('#openingName').fill('123456789');await page.locator('#openingDecide').click();assert(await page.locator('#openingName').count());await page.locator('#openingName').fill('スラちゃん');await page.locator('#openingDecide').click();}
  else if(await page.locator('#openingYes').count()){if(!noChecked){await page.locator('#openingNo').click();assert(await page.locator('#openingYes').count());noChecked=true;}await page.locator('#openingYes').click();}
  else {await page.locator('#openingText').click();await page.locator('#openingNext').click();}
 }
 assert.equal(await page.locator('[data-home-mon]').count(),1);assert(await page.evaluate(()=>T.state().flags.roboOwned&&T.state().owned[0].level===5&&T.state().owned[0].nickname==='スラちゃん'));
 // Old saves: retain real souls and collapse only test-created surplus.
 const realId=await page.evaluate(()=>{const s=T.state();s.settings={testMode:true,soulsMax:true};s.souls={};for(const m of MOBMON_DATA.monsters){s.souls[m.name]=Array.from({length:10},(_,i)=>({id:'test_'+m.no+'_'+i,name:m.name,source:'test',records:[],cassette:0,lineage:[]}));}T.addSoul('モブスライム',{source:'drop'});const real=s.souls['モブスライム'].at(-1).id;s.testRestore={souls:{}};T.save();return real;});
 assert(await page.evaluate(id=>Object.values(T.state().souls).every(a=>a.length===2)&&T.state().souls['モブスライム'].some(s=>s.id===id),realId));
 await page.evaluate(()=>{T.go('soul');T.soulBankV6(document.querySelector('#screen'));});assert.equal(await page.locator('#soulGrid [data-soul-index]').count(),30);assert.equal(await page.locator('#soulGrid img').count(),30);await page.locator('#soulNext').click();assert.equal(await page.locator('#soulPager span').innerText(),'2 / 15');await page.waitForTimeout(1900);await page.screenshot({path:'tests/screenshots/033-souls.png'});
 await page.reload();await page.locator('#continueGame').click();assert(await page.evaluate(id=>T.state().souls['モブスライム'].some(s=>s.id===id)&&Object.values(T.state().souls).every(a=>a.length===2),realId));
 await page.evaluate(()=>{T.state().settings.testMode=false;T.applyTestV6();T.save();});assert(await page.evaluate(id=>T.state().souls['モブスライム'].some(s=>s.id===id)&&Object.values(T.state().souls).flat().every(s=>s.source!=='test'),realId));
 // Monster conversion preserves metadata and forbids equipped party members.
 const monsterId=await page.evaluate(()=>{const m=T.createInstance('モブロック',12);m.cassette=7;m.records[0].level=32;m.lineage=['test-lineage'];T.state().owned.push(m);T.save();T.go('soul');return m.uid;});
 await page.locator('#labMonsterSoul').click();assert(await page.locator('[data-exchange]').first().isDisabled());await page.locator('[data-exchange]').nth(1).click();await page.locator('#answerNo').click();assert(await page.evaluate(id=>T.state().owned.some(m=>m.uid===id),monsterId));await page.locator('[data-exchange]').nth(1).click();await page.locator('#answerYes').click();await page.locator('#exchangeDone').waitFor();assert(await page.evaluate(id=>!T.state().owned.some(m=>m.uid===id)&&T.state().souls['モブロック'].some(s=>s.cassette===7&&s.records[0].level===32&&s.lineage[0]==='test-lineage'),monsterId));await page.screenshot({path:'tests/screenshots/033-conversion.png'});await page.locator('#exchangeDone').click();
 await page.locator('#labSoulRuby').click();await page.locator('[data-exchange]').first().click();await page.locator('#answerYes').click();await page.locator('#exchangeDone').waitFor();assert(await page.evaluate(()=>T.state().rubies>0));await page.locator('#exchangeDone').click();await page.reload();await page.locator('#continueGame').click();assert(await page.evaluate(()=>T.state().rubies>0));
 for(const screen of ['shop','gacha']){await page.evaluate(screen=>T.go(screen),screen);await page.waitForTimeout(2000);const selector=screen==='shop'?'#meetMerchant':'#drawSticker';assert(await page.locator(selector).isVisible());assert(await page.locator(selector).evaluate((e,selector)=>{const r=e.getBoundingClientRect();return !!document.elementFromPoint(r.x+r.width/2,Math.min(innerHeight-90,r.y+r.height/2))?.closest(selector)},selector));await page.screenshot({path:`tests/screenshots/033-${screen}.png`});if(screen==='shop'){await page.locator('#meetMerchant').click();assert.equal(await page.locator('[data-shop]').count(),4);}}
 await page.locator('#drawSticker').click();await page.locator('#answerYes').click();await page.locator('#modalClose').click();
 const checks=await page.evaluate(()=>{const c=MOBMON_CAMPAIGN,x=T.exploration;for(const e of c.entries){for(let floor=1;floor<=4;floor++){const f=x.generate(e.area,e.deep,floor);for(const m of f.entities.filter(m=>m.level)){const [a,b]=c.range(e.area,e.deep,floor,m.kind,false);if(m.level<a||m.level>b)throw Error('field level');}if(floor<4){const cave=x.generateCave(e.area,e.deep,floor);const [a,b]=c.range(e.area,e.deep,floor,'enemy',true);if(!cave.entities.filter(m=>m.level).every(m=>m.level>=a&&m.level<=b))throw Error('cave level');}}const enemy=T.buildRuntimeEnemy({name:MOBMON_DATA.areaBoss[e.area][e.deep?'2':'1'],level:e.boss},0);if(enemy.level!==e.boss)throw Error('boss clamped');}const enemy120=T.buildRuntimeEnemy({name:'モブナビマスター',level:120},0),enemy99=T.buildRuntimeEnemy({name:'モブナビマスター',level:99},0);if(enemy120.maxHp<=enemy99.maxHp)throw Error('stats clamped');const cleared=new Set();if(c.unlocked('ネオン街',false,(a,d)=>cleared.has(a+'|'+d)))throw Error('early unlock');for(const a of ['草原','砂漠','田舎町'])cleared.add(a+'|false');if(!c.unlocked('ネオン街',false,(a,d)=>cleared.has(a+'|'+d)))throw Error('season lock');return c.entries.length;});assert.equal(checks,18);
 await page.evaluate(()=>{T.go('home');T.go('story');});await page.locator('[data-destination]').first().click();await page.locator('#normalDepth').click();await page.locator('#answerYes').click();await page.locator('.journey-overlay').waitFor({state:'detached'});assert.equal(await page.locator('.field-nameplate').count(),7);await page.screenshot({path:'tests/screenshots/033-field.png'});
 const matched=await page.evaluate(()=>{const x=T.exploration,e=x.field().entities.find(e=>e.kind==='enemy');x.interact(e);return {name:e.name,level:e.level};});await page.waitForFunction(()=>!!T.battle());assert.deepEqual(await page.evaluate(()=>({name:T.battle().enemyRoster[0].name,level:T.battle().enemyRoster[0].level})),matched);assert(await page.locator('.enemy-overhead').first().innerText());await page.screenshot({path:'tests/screenshots/033-battle.png'});

 await page.evaluate(()=>{T.endBattleToScreen(false,false);T.state().settings.testMode=true;T.save();T.go('settings');});await page.locator('#returnTitle').click();await page.locator('#seedBtn').click();await page.locator('#answerYes').click();await page.locator('#openingSkip').click();await page.locator('#answerNo').click();assert(await page.locator('.opening-screen').count());await page.locator('#openingSkip').click();await page.locator('#answerYes').click();assert.equal(await page.locator('[data-home-mon]').count(),1);assert(await page.evaluate(()=>T.state().opening.complete&&T.state().flags.roboOwned));
 await page.evaluate(()=>{for(let i=0;i<12;i++)T.addSoul('モブスライム',{source:'drop'});T.state().settings.soulsMax=true;T.save();});assert.equal(await page.evaluate(()=>T.state().souls['モブスライム'].length),12);
 const beforeReward=await page.evaluate(()=>{T.state().settings.testMode=false;T.applyTestV6();for(let i=0;i<3;i++)T.state().owned.push(T.createInstance('モブロック',5));T.save();T.go('castle');return {gold:T.state().gold,diamonds:T.state().diamonds};});
 await page.locator('#lilithTalk').click();assert.deepEqual(await page.evaluate(()=>({gold:T.state().gold,diamonds:T.state().diamonds})),{gold:beforeReward.gold+3000,diamonds:beforeReward.diamonds+10});await page.locator('#modalClose').click();await page.locator('#lilithTalk').click();assert.equal(await page.evaluate(()=>T.state().gold),beforeReward.gold+3000);await page.locator('#modalClose').click();await page.locator('#lilithHelp').click();assert.equal(await page.locator('.help-topic').count(),8);
 assert.deepEqual(errors,[]);console.log('033: opening/resume, test soul migration, pagination, conversions, facilities, 18 campaign entries/caves, Lv120 stats, labels and contact level OK');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
