/* Production UI source, assembled inside the core closure by install-ui.cjs. */
let uiBusy=false,modalCancel=null;
const ui={partySort:'level',soulSort:'rank',slot:null,fusion:[null,null],pending:null};
state.settings={battleSpeed:1,...state.settings};
state.diamonds=Number(state.diamonds)||0;state.soulPoints=Number(state.soulPoints)||0;
state.seen={...state.seen};state.owned.forEach(m=>state.seen[m.name]=true);
state.stickers=state.stickers||{};
const rolesV6=[['メイン',0,4,'main'],['スーパーサブ',4,6,'super'],['控え',6,10,'reserve']];
const uiAssets={lilith:'play/14.png',chibiLilith:'play/14.png',...window.MOBMON_UI_ASSETS};
function headingV6(title,kicker,back='home'){return `<header class="page-heading"><button class="back-v6" data-go="${back}" aria-label="戻る">‹</button><div><small>${kicker}</small><h1>${title}</h1></div></header>`;}
function askV6(title,description='',cancel=false){
  return new Promise(resolve=>{showModal(title,`<div class="confirm-v6"><span class="confirm-emblem">✦</span><p>${esc(description)}</p><div class="button-row"><button id="answerNo" class="ghost-btn">いいえ</button><button id="answerYes" class="primary">はい</button></div>${cancel?'<button id="answerCancel" class="ghost-btn full">キャンセル（A/B解除）</button>':''}</div>`);
    let settled=false;const done=value=>{if(settled)return;settled=true;modalCancel=null;$('#modal').hidden=true;resolve(value);};modalCancel=done;
    $('#answerYes').onclick=()=>done(true);$('#answerNo').onclick=()=>done(false);if(cancel)$('#answerCancel').onclick=()=>done('cancel');
  });
}
document.addEventListener('keydown',e=>{if($('#modal').hidden)return;if(e.key==='Escape'){e.preventDefault();closeModal();}if(e.key==='Tab'){const nodes=$$('button:not(:disabled),input,select,[tabindex="0"]',$('#modal'));if(!nodes.length)return;const i=nodes.indexOf(document.activeElement);e.preventDefault();nodes[(i+(e.shiftKey?-1:1)+nodes.length)%nodes.length].focus({preventScroll:true});}});
function lilithV6(chibi=false){return `<span class="lilith-art ${chibi?'chibi':''}">${assetImgMarkup(chibi?uiAssets.chibiLilith:uiAssets.lilith,'リリス')}<span class="lilith-halo"></span></span>`;}
function homeV6(root){
 root.className='screen home-v6';const cur=state.story.current;
 root.innerHTML=`<div class="home-world">${sceneBgMarkup('home')}<div class="world-shade"></div><div class="home-heading"><small>OUR MONSTERS, OUR STORY</small><h1>おかえり、冒険者。</h1><span>仲間とつなぐ、ソウルの物語</span></div><button class="home-letter" data-go="castle">✦ リリスからの案内 <span>›</span></button><div class="home-company">${[rolesV6[2],rolesV6[1],rolesV6[0]].map(([label,from,to,cls])=>`<section class="company-row ${cls}"><small>${label} <span>${to-from}</span></small><div>${Array.from({length:to-from},(_,j)=>{const inst=ownedByUid(state.party[from+j]);return `<button class="company-member" ${inst?`data-home-mon="${inst.uid}"`:'data-go="party"'} style="--delay:${j*-.63}s">${stageArtMarkup(monsterDef(inst))}<b>${inst?esc(inst.name):'仲間を編成'}</b><em>${inst?'Lv '+inst.level:'＋'}</em></button>`;}).join('')}</div></section>`).join('')}</div><aside class="home-facilities" aria-label="施設メニュー">${[['castle','♜','お城','LILITH'],['shop','▣','MOB SHOP','ITEMS'],['story','⚑','冒険','QUEST'],['soul','✦','ソウルラボ','SOUL LAB'],['gacha','◇','ガチャ','STICKERS']].map(([go,icon,label,en])=>`<button data-go="${go}" class="facility ${go}"><i>${icon}</i><b>${label}</b><small>${en}</small></button>`).join('')}</aside><div class="home-bottom"><div class="company-status"><span>MY PARTY <b>${currentParty().length}/10</b></span><span>COLLECTION <b>${state.owned.length}</b></span><button data-go="arena">♛ 闘技場 ›</button></div><button class="adventure-banner" data-go="story"><span><small>${state.story.resume?'冒険を再開':'NEXT ADVENTURE'} / SEASON ${cur.season}</small><b>${esc(cur.area)} <em>${cur.floor}F・AREA ${cur.areaNo}</em></b></span><strong>冒険へ ›</strong></button></div></div>`;
 $$('[data-home-mon]').forEach(b=>b.onclick=()=>openMonsterDetail(b.dataset.homeMon));
}
function castleV6(root){root.className='screen castle-v6';const c=state.story.current;root.innerHTML=headingV6('リリスの玉座','LILITH’S CASTLE')+`<section class="lilith-scene castle">${sceneBgMarkup('floor','魔王城',1)}<div class="throne"></div>${lilithV6()}<div class="speech"><small>リリス</small><p>${currentParty().length<4?'まずはメインに4体の仲間を編成してみよう。君だけの部隊が、冒険の力になるよ。':`次は${esc(c.area)}の${c.floor}F、AREA ${c.areaNo}へ。仲間を育てながら、一緒に先へ進もう。`}</p></div></section><button class="primary full" data-go="${currentParty().length<4?'party':'story'}">${currentParty().length<4?'仲間を編成する':'次の冒険へ'}</button><button class="ghost-btn full" data-go="arena">闘技場に挑戦</button>`;}
function sortV6(list,key){return [...list].sort((a,b)=>{const ma=monsterByName.get(a.name),mb=monsterByName.get(b.name);return (key==='level'?(b.level||0)-(a.level||0):key==='rank'?rankIndex(mb.rank)-rankIndex(ma.rank):String(ma[key]||'').localeCompare(String(mb[key]||''),'ja'))||ma.no-mb.no;});}
function sortMarkupV6(id,value,soul=false){return `<label class="sort-v6">並び替え <select id="${id}">${(soul?[['rank','ランク'],['species','種族'],['attribute','属性'],['name','名前']]:[['level','レベル'],['species','種族'],['rank','ランク'],['attribute','属性']]).map(([v,t])=>`<option value="${v}" ${v===value?'selected':''}>${t}</option>`).join('')}</select></label>`;}
function tileV6(inst,attr='data-owned'){const m=monsterDef(inst),pi=state.party.indexOf(inst.uid);return `<button class="square-mon ${pi>=0?'assigned':''}" ${attr}="${inst.uid}" aria-label="${esc(inst.name)} レベル${inst.level}"><span class="tile-rank">${m.rank}</span>${cardArtMarkup(m)}<b>${esc(inst.name)}</b><small>Lv ${inst.level}${pi>=0?' • 編成中':''}</small></button>`;}
function partyV6(root){
 root.className='screen party-v6';root.innerHTML=headingV6('パーティー編成','YOUR COMPANY / 4 + 2 + 4')+`<p class="instruction-v6">枠を2つタップして入れ替え。長押しで移動もできます。</p><div id="formationV6"></div><section class="roster-section"><div class="roster-heading"><h2>所持モンスター <small>${state.owned.length}</small></h2>${sortMarkupV6('partySort',ui.partySort)}</div><p id="partyHint" class="instruction-v6">仲間をタップして詳細・編成・育成へ</p><div id="rosterV6" class="five-grid"></div></section>`;
 drawFormationV6();drawRosterV6();$('#partySort').onchange=e=>{ui.partySort=e.target.value;drawRosterV6();};
}
function drawFormationV6(){const host=$('#formationV6');if(!host)return;host.innerHTML=rolesV6.map(([label,from,to,cls])=>`<section class="formation-v6 ${cls}"><header><b>${label}</b><small>${cls==='main'?'FRONT LINE':cls==='super'?'AUTO SUPPORT':'RESERVE'}</small></header><div class="formation-row">${Array.from({length:to-from},(_,j)=>{const i=from+j,inst=ownedByUid(state.party[i]);return `<button class="formation-cell ${ui.slot===i?'selected':''}" data-slot="${i}" aria-label="${label}${j+1} ${inst?esc(inst.name):'空き枠'}" aria-pressed="${ui.slot===i}">${slotArtMarkup(monsterDef(inst))}<b>${inst?esc(inst.name):'＋ 編成'}</b><small>${inst?'Lv '+inst.level:'EMPTY'}</small><em>${j+1}</em></button>`;}).join('')}</div></section>`).join('');
 $$('[data-slot]').forEach(b=>{b.onclick=()=>{const n=Number(b.dataset.slot);if(ui.slot===null){ui.slot=n;drawFormationV6();$('#partyHint').textContent='光っている枠へ配置します。所持モンスターを選んでください。';}else if(ui.slot===n){ui.slot=null;drawFormationV6();}else{const old=state.party[ui.slot]||null;state.party[ui.slot]=state.party[n]||null;state.party[n]=old;ui.slot=null;save();drawFormationV6();drawRosterV6();toast('配置を入れ替えました');}};
 let timer=null,dragging=false;b.onpointerdown=e=>{if(e.pointerType==='mouse'&&e.button!==0)return;timer=setTimeout(()=>{dragging=true;b.classList.add('dragging');b.setPointerCapture?.(e.pointerId);},350);};b.onpointermove=e=>{if(dragging){e.preventDefault();}};b.onpointercancel=()=>{clearTimeout(timer);dragging=false;b.classList.remove('dragging');};b.onpointerup=e=>{clearTimeout(timer);if(!dragging)return;dragging=false;b.classList.remove('dragging');const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]');if(target&&target!==b){const a=Number(b.dataset.slot),n=Number(target.dataset.slot),old=state.party[a]||null;state.party[a]=state.party[n]||null;state.party[n]=old;ui.slot=null;save();drawFormationV6();drawRosterV6();toast('配置を入れ替えました');}b.onclick=null;};});
}
function drawRosterV6(){const host=$('#rosterV6');if(!host)return;host.innerHTML=sortV6(state.owned,ui.partySort).map(i=>tileV6(i)).join('')||'<p class="empty-v6">まだ仲間がいません。ソウルフュージョンで仲間を迎えよう。</p>';$$('[data-owned]').forEach(b=>b.onclick=()=>openMonsterDetail(b.dataset.owned));}
async function assignV6(id){const inst=ownedByUid(id);if(!inst)return;const index=ui.slot??Array.from({length:10},(_,i)=>i).find(i=>!ownedByUid(state.party[i]));if(index===undefined){closeModal();showModal('配置先を選んでください',`<p class="instruction-v6">10体編成中です。入れ替える枠を選んでください。</p><div class="five-grid">${Array.from({length:10},(_,i)=>`<button class="destination" data-dest="${i}">${roleLabel(i)} ${i+1}<b>${esc(ownedByUid(state.party[i])?.name||'空き')}</b></button>`).join('')}</div>`);$$('[data-dest]').forEach(b=>b.onclick=()=>{ui.slot=Number(b.dataset.dest);assignV6(id);});return;}
 if(!await askV6('パーティーに加えますか？',`${inst.name}を${rolesV6.find(r=>index>=r[1]&&index<r[2])[0]} ${index+1}に配置します。`))return;
 const old=state.party[index]||null,other=state.party.indexOf(id);if(other>=0)state.party[other]=old;state.party[index]=id;ui.slot=null;save();if(state.screen==='party'){drawFormationV6();drawRosterV6();}toast('仲間を配置しました');
}
function labV6(root){ui.fusion=[null,null];root.className='screen lab-v6';root.innerHTML=headingV6('ソウルラボ','SOUL LABORATORY')+`<section class="lilith-scene lab">${sceneBgMarkup('soul')}<div class="lab-stars">✦ · ✧ · ✦</div><button id="lilithMenu" class="lilith-touch" aria-label="ちびリリスに話しかける">${lilithV6(true)}<span>ちびリリスにタップ</span></button><div class="speech"><small>ちびリリス</small><p>集めたソウルには、まだ知らない可能性が眠っているよ。</p></div></section><p class="lab-caption">ふたつの魂が出会うとき、新しい仲間が生まれる。</p>`;$('#lilithMenu').onclick=()=>{showModal('ちびリリスのソウルラボ','<div class="lab-menu"><button id="openSoulBank"><span>◈</span><b>ソウルを確認</b><small>集めた魂を見てみよう ›</small></button><button id="openSoulFusion"><span>✦</span><b>ソウルフュージョン</b><small>新しい仲間を迎える ›</small></button></div>');$('#openSoulBank').onclick=()=>{closeModal();soulBankV6(root);};$('#openSoulFusion').onclick=()=>{closeModal();fusionV6(root);};};}
function soulCardV6(s,i){const m=monsterByName.get(s.name);return `<button class="square-mon soul-tile" data-soul-index="${i}"><span class="tile-rank">${m.rank}</span><span class="soul-echo">${cardArtMarkup(m)}</span>${cardArtMarkup(m)}<b>${esc(s.name)}</b><small>SOUL · ${esc(m.attribute)}</small></button>`;}
function soulBankV6(root,selectSlot=null){const selecting=selectSlot!==null;root.className='screen soul-bank-v6';root.innerHTML=headingV6(selecting?`SOUL ${selectSlot===0?'A':'B'}を選択`:'ソウルを確認','SOUL COLLECTION','soul')+`<button id="soulBack" class="ghost-btn full">‹ ${selecting?'フュージョンへ戻る':'ラボへ戻る'}</button><div class="roster-heading"><p>所持 ${Object.values(state.souls).flat().length} SOUL</p>${sortMarkupV6('soulSort',ui.soulSort,true)}</div><div id="soulGrid" class="five-grid"></div>`;
 const draw=()=>{const list=sortV6(Object.values(state.souls).flat(),ui.soulSort);$('#soulGrid').innerHTML=list.map((s,i)=>soulCardV6(s,i)).join('')||'<p class="empty-v6">ソウルは冒険で手に入ります。</p>';$$('[data-soul-index]').forEach(b=>b.onclick=async()=>{const s=list[Number(b.dataset.soulIndex)];if(selecting){if(ui.fusion[1-selectSlot]?.id===s.id)return toast('もう一方で選択中のソウルです');if(!await askV6('このソウルを使いますか？',`${s.name} / ${monsterByName.get(s.name).rank}ランク`))return;ui.fusion[selectSlot]=s;fusionV6(root);if(ui.fusion.every(Boolean))scanFusionV6();}else{showModal(s.name,`<div class="soul-info">${soulCardV6(s,0)}<p>${esc(monsterByName.get(s.name).species)} / ${esc(monsterByName.get(s.name).attribute)}</p><h3>継承の記録</h3>${(s.records||[]).map(r=>`<p>${esc(r.name)} Lv ${r.level}</p>`).join('')}<p>${esc((s.lineage||[]).join(' / '))}</p><button id="soulInfoBack" class="ghost-btn full">戻る</button></div>`);$('#soulInfoBack').onclick=closeModal;}});};draw();$('#soulSort').onchange=e=>{ui.soulSort=e.target.value;draw();};$('#soulBack').onclick=()=>selecting?fusionV6(root):labV6(root);}
function fusionV6(root){root.className='screen fusion-v6';root.innerHTML=headingV6('ソウルフュージョン','TWO SOULS, ONE NEW STORY','soul')+`<section class="fusion-sanctum ${ui.fusion.every(Boolean)?'ready':''}">${sceneBgMarkup('soul')}<div class="fusion-intro"><small>SOUL FUSION</small><h2>新しい命を、ここに。</h2><p>ふたつのソウルを選んでください</p></div><div class="fusion-pair">${ui.fusion.map((s,i)=>`<button class="fusion-source" data-fusion-slot="${i}"><small>SOUL ${i===0?'A':'B'}</small>${s?stageArtMarkup(monsterByName.get(s.name)):'<span class="source-plus">＋</span>'}<b>${s?esc(s.name):'ソウルを選ぶ'}</b></button>`).join('<div class="reactor-v6">✦</div>')}</div><p class="fusion-footnote">ふたつのソウルを消費して、Lv 1の仲間が誕生します。</p></section><button id="scanFusion" class="primary full" ${ui.fusion.every(Boolean)?'':'disabled'}>フュージョンへ進む</button><button id="clearFusion" class="ghost-btn full">A / B を解除</button><div id="candidatesV6"></div>`;$$('[data-fusion-slot]').forEach(b=>b.onclick=()=>soulBankV6(root,Number(b.dataset.fusionSlot)));$('#scanFusion').onclick=scanFusionV6;$('#clearFusion').onclick=()=>{ui.fusion=[null,null];fusionV6(root);};}
function withSelectedSoulsV6(fn){const old=state.souls,selected={};for(const s of ui.fusion){if(!s)continue;(selected[s.name]||=[]).push(s);}state.souls=selected;try{return fn();}finally{state.souls=old;}}
async function scanFusionV6(){if(!ui.fusion.every(Boolean))return;const yes=await askV6('ソウルフュージョンを行いますか？','誕生できる仲間を確認します。ソウルはまだ消費しません。',true);if(yes==='cancel'){ui.fusion=[null,null];fusionV6($('#screen'));return;}if(!yes)return;const [a,b]=ui.fusion;const candidates=withSelectedSoulsV6(()=>fusionCandidates(a.name,b.name));$('#candidatesV6').innerHTML=`<div class="roster-heading"><h2>誕生する仲間を選択</h2><small>${candidates.length} CANDIDATES</small></div><div class="candidate-grid">${candidates.map((x,i)=>{const known=!!state.seen[x.name],m=monsterByName.get(x.name);return `<button class="candidate-v6 ${known?'':'unseen'}" data-candidate="${i}"><span>${esc(x.kind)}</span>${known?stageArtMarkup(m):stageArtMarkup({...m,name:'???',image:monsterImage(m)})}<b>${known?esc(x.name):'???'}</b><small>${m.rank} / ${known?esc(m.species):'未発見のモンスター'}</small></button>`;}).join('')||'<p>この組み合わせの候補はありません。</p>'}</div>`;$$('[data-candidate]').forEach(btn=>btn.onclick=async()=>{const c=candidates[Number(btn.dataset.candidate)];if(await askV6('このモンスターを誕生させますか？',state.seen[c.name]?c.name:'??? — まだ出会っていない仲間'))inheritV6(c);});}
function inheritableV6(a,b,result){const native=new Set(monsterByName.get(result).nativeRecords||[]),names=new Set();for(const s of [a,b])for(const r of s.records||[])if(r.level>=30&&!native.has(r.name))names.add(r.name);for(const r of D.recordFusions){const has=(s,n)=>(s.records||[]).some(x=>x.name===n&&x.level>=70);if(((has(a,r.a)&&has(b,r.b))||(has(a,r.b)&&has(b,r.a)))&&!native.has(r.result))names.add(r.result);}return [...names];}
function inheritV6(candidate){const [a,b]=ui.fusion,records=inheritableV6(a,b,candidate.name);showModal('継承する力を選択',`<p class="instruction-v6">条件を満たしたソウルレコードを選べます。固有パッシブは継承されません。</p><div class="inherit-list">${records.map((r,i)=>`<label><input type="checkbox" data-inherit="${i}" checked><span>✦ ${esc(r)}<small>Lv 1で継承</small></span></label>`).join('')||'<p class="empty-v6">継承できる力はありません。固有のレコードを持って誕生します。</p>'}</div><button id="birthDecide" class="primary full">決定・ソウルを消費して合体</button>`);$('#birthDecide').onclick=()=>birthV6(candidate,records.filter((_,i)=>$(`[data-inherit="${i}"]`)?.checked));}
async function birthV6(candidate,records){if(uiBusy)return;const [a,b]=ui.fusion;if(!a||!b||a.id===b.id)return;for(const s of [a,b])if(!(state.souls[s.name]||[]).some(x=>x.id===s.id))return toast('選択したソウルが見つかりません');const valid=withSelectedSoulsV6(()=>fusionCandidates(a.name,b.name)).find(x=>x.name===candidate.name&&x.recipeNo===candidate.recipeNo);if(!valid)return toast('候補を選び直してください');const child=createInstance(candidate.name,1,false),allowed=new Set(inheritableV6(a,b,candidate.name));for(const name of records)if(allowed.has(name))child.records.push({name,level:1,exp:0});child.lineage=[...new Set([...(a.lineage||[]),...(b.lineage||[])])];const recipe=candidate.recipeNo?D.fixedFusions.find(r=>String(r.no)===String(candidate.recipeNo)):null;if(recipe?.grantLineage&&!child.lineage.includes(recipe.grantLineage))child.lineage.push(recipe.grantLineage);
 // Commit both souls and the child together before presentation; reloading never loses a birth.
 const previous=JSON.stringify(state);for(const s of [a,b])state.souls[s.name]=state.souls[s.name].filter(x=>x.id!==s.id);state.owned.push(child);state.seen[child.name]=true;try{save();}catch{state=JSON.parse(previous);return toast('保存できませんでした。ソウルは消費していません。');}
 uiBusy=true;showModal('SOUL FUSION',`<div class="birth-v6 merging"><div class="birth-parent left">${stageArtMarkup(monsterByName.get(a.name))}</div><div class="birth-parent right">${stageArtMarkup(monsterByName.get(b.name))}</div><div class="birth-light"></div><span class="rising-sparks">✦ · ✧ · ✦</span><h2>魂が、ひとつになる。</h2></div>`);await sleep(850);$('.birth-v6')?.classList.add('illuminated');await sleep(3000);uiBusy=false;showModal('新しい仲間が誕生！',`<section class="birth-v6 born">${stageArtMarkup(monsterByName.get(child.name))}<small>NEW COMPANION</small><h2>${esc(child.name)}</h2><p>Lv 1 / ${esc(monsterDef(child).rank)} RANK</p><p>パーティーに加えますか？</p><div class="button-row"><button id="birthNo" class="ghost-btn">いいえ</button><button id="birthYes" class="primary">はい</button></div></section>`);ui.fusion=[null,null];$('#birthNo').onclick=()=>{closeModal();labV6($('#screen'));};$('#birthYes').onclick=()=>{ui.pending=child.uid;go('party');openMonsterDetail(child.uid);};}
function recordCostV6(r,count){let cost=-(r.exp||0);for(let n=0;n<count;n++)cost+=nextRecordExp(r.level+n);return Math.max(0,cost);}
function trainingV6(id,recordName=null,count=1){const inst=ownedByUid(id);if(!inst)return;const record=(inst.records||[]).find(r=>r.name===recordName)||activeRecord(inst);if(!record)return toast('育成できるソウルレコードがありません');count=clamp(count,0,70-record.level);const cost=recordCostV6(record,count),enough=state.soulPoints>=cost;showModal('ソウルレコード育成',`<section class="training-v6"><div class="training-emblem">✦</div><small>SOUL RECORD</small><h2>${esc(record.name)}</h2><label>育成レコード<select id="trainingRecord">${inst.records.map(r=>`<option value="${esc(r.name)}" ${r===record?'selected':''}>${esc(r.name)} / Lv ${r.level}</option>`).join('')}</select></label><div class="level-route">Lv ${record.level}<span>→</span><b>${record.level+count>=70?'MASTER':`Lv ${record.level+count}`}</b></div><div class="level-stepper"><button id="levelMinus" ${count<=1?'disabled':''} aria-label="レベル数を減らす">−</button><b>＋ ${count}</b><button id="levelPlus" ${record.level+count>=70?'disabled':''} aria-label="レベル数を増やす">＋</button></div><p class="point-cost ${enough?'':'insufficient'}">必要 ${fmt(cost)} SP / 所持 ${fmt(state.soulPoints)} SP</p><small>${enough?'ソウルポイントを消費して育成':'ソウルポイントが足りません'}</small><button id="levelExecute" class="primary full" ${!enough||!count?'disabled':''}>${record.level>=70?'MASTER 達成':'レベルアップ'}</button><button id="trainingBack" class="ghost-btn full">モンスター詳細へ戻る</button></section>`);$('#trainingRecord').onchange=e=>trainingV6(id,e.target.value);$('#levelMinus').onclick=()=>trainingV6(id,record.name,count-1);$('#levelPlus').onclick=()=>trainingV6(id,record.name,count+1);$('#trainingBack').onclick=()=>openMonsterDetail(id);$('#levelExecute').onclick=async()=>{if(!await askV6('レベルアップしますか？',`${record.name} Lv ${record.level} → ${record.level+count} / ${fmt(cost)} SPを消費します。`))return trainingV6(id,record.name,count);if(state.soulPoints<cost)return trainingV6(id,record.name,count);state.soulPoints-=cost;record.level+=count;record.exp=0;save();showModal('LEVEL UP',`<div class="training-v6 level-up"><div class="training-emblem">✦</div><span class="rising-sparks">✧ · ✦ · ✧</span><small>力が、目を覚ます。</small><h2>${esc(record.name)}</h2><div class="level-route">Lv ${record.level} ${record.level>=70?'MASTER':''}</div><p>LEVEL UP ＋${count}</p><button id="levelDone" class="primary full">育成を続ける</button></div>`);$('#levelDone').onclick=()=>trainingV6(id,record.name);};}
const testSettingsV6=[['testMode','テストモード','テスト機能の一括有効化・停止'],['fastBattle','5倍速度戦闘','戦闘中の演出と待機時間を短縮'],['itemsMax','アイテムMAX','各アイテムを999個に補充'],['goldMax','コインMAX','9,999,999 Gに補充'],['diamondsMax','ダイヤMAX','9,999,999個に補充'],['soulsMax','所持ソウルMAX','全213種を各10個に補充'],['pointsMax','ソウルポイントMAX','9,999,999 SPに補充']];
function applyTestV6(){const s=state.settings;state.testRestore=state.testRestore||{};const restore=state.testRestore;for(const [flag,key,value] of [['itemsMax','inventory',Object.fromEntries(Object.keys(state.inventory).map(k=>[k,999]))],['goldMax','gold',9999999],['diamondsMax','diamonds',9999999],['pointsMax','soulPoints',9999999],['soulsMax','souls',null]]){const active=s.testMode&&s[flag];if(active){if(!(key in restore))restore[key]=JSON.parse(JSON.stringify(state[key]));if(key==='souls'){for(const m of D.monsters){const list=state.souls[m.name]||=[];while(list.length<10)list.push(soulToken(m.name,{source:'test'}));}}else state[key]=value;}else if(key in restore){if(key==='souls'){for(const name of Object.keys(state.souls))state.souls[name]=state.souls[name].filter(t=>t.source!=='test');for(const [name,tokens]of Object.entries(restore.souls)){const list=state.souls[name]||=[];for(const t of tokens)if(!list.some(s=>s.id===t.id))list.push(t);}}else state[key]=restore[key];delete restore[key];}}state.settings.battleSpeed=s.testMode&&s.fastBattle?5:1;}
function settingsV6(root){root.className='screen settings-v6';root.innerHTML=headingV6('設定','SETTINGS')+`<section class="settings-intro"><span>⚙</span><div><h2>冒険の設定</h2><p>テスト用の資源はOFF時に元の数量へ戻ります。<br>獲得・育成したモンスターは保持されます。</p></div></section><div class="settings-list">${testSettingsV6.map(([key,label,note])=>`<button class="setting-toggle" data-setting="${key}" role="switch" aria-checked="${!!state.settings[key]}" ${key!=='testMode'&&!state.settings.testMode?'disabled':''}><span><b>${label}</b><small>${note}</small></span><em>${state.settings[key]?'ON':'OFF'}</em><i class="switch-track"><u></u></i></button>`).join('')}</div><p class="instruction-v6">ソウルポイントは戦闘でも獲得できます。<br>ダイヤ ${fmt(state.diamonds)} / SP ${fmt(state.soulPoints)}</p><button class="ghost-btn full" id="saveExport">セーブデータを書き出す</button>`;$$('[data-setting]').forEach(b=>b.onclick=async()=>{const key=b.dataset.setting,value=!state.settings[key];if(value&&!await askV6(`${testSettingsV6.find(x=>x[0]===key)[1]}をONにしますか？`,'設定は保存され、次回も引き継がれます。'))return;state.settings[key]=value;applyTestV6();save();settingsV6(root);});$('#saveExport').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=url;a.download='MOB-MONSTERS-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};}
function shopV6(root){root.className='screen shop-v6';root.innerHTML=headingV6('MOB SHOP','SUPPLIES FOR YOUR JOURNEY')+`<section class="shop-intro"><span>▣</span><h2>冒険の準備をしよう。</h2><p>所持コイン <b>${fmt(state.gold)} G</b></p></section><div class="shop-list">${D.soulBoostItems.map((it,i)=>`<button class="shop-item" data-shop="${i}"><span>♪</span><div><b>${esc(it.name)}</b><small>ソウルドロップ率 +${Math.round(it.add*100)}% / 所持 ${state.inventory[it.id]||0}</small></div><em>${fmt((i+1)*200)} G</em></button>`).join('')}</div><button id="useItems" class="ghost-btn full">所持アイテムを使う</button>`;$$('[data-shop]').forEach(b=>b.onclick=async()=>{const i=Number(b.dataset.shop),it=D.soulBoostItems[i],cost=(i+1)*200;if(state.gold<cost)return toast('コインが足りません');if(!await askV6('このアイテムを購入しますか？',`${it.name} 1個 / ${cost} G`))return;if(state.gold<cost)return;state.gold-=cost;state.inventory[it.id]=(state.inventory[it.id]||0)+1;save();shopV6(root);toast('購入しました');});$('#useItems').onclick=()=>{showModal('ソウルドロップを強化',D.soulBoostItems.map((it,i)=>`<button class="shop-item" data-use="${i}" ${state.inventory[it.id]>0?'':'disabled'}><b>${esc(it.name)}</b><small>所持 ${state.inventory[it.id]||0}</small></button>`).join(''));$$('[data-use]').forEach(b=>b.onclick=async()=>{const it=D.soulBoostItems[Number(b.dataset.use)];if(!await askV6('このアイテムを使いますか？',`${it.name}を1個消費します。`))return;if(!(state.inventory[it.id]>0))return;state.inventory[it.id]--;state.soulBoost+=it.add;save();toast('ソウルドロップ率を強化しました');shopV6(root);});};}
function gachaV6(root){root.className='screen gacha-v6';root.innerHTML=headingV6('シールガチャ','MONSTER STICKERS')+`<section class="gacha-stage"><span class="gacha-gem">◇</span><small>STICKER COLLECTION</small><h2>小さな一枚、大きな出会い。</h2><p>おためしシールガチャ</p><button id="drawSticker" class="primary full">無料で1回引く</button><small>テスト提供中・通貨の消費はありません</small></section><div class="roster-heading"><h2>マイシール</h2><small>${Object.keys(state.stickers).length}種類</small></div><div class="five-grid">${Object.entries(state.stickers).map(([name,n])=>`<article class="sticker">${cardArtMarkup(monsterByName.get(name))}<b>${esc(name)}</b><small>×${n}</small></article>`).join('')}</div>`;$('#drawSticker').onclick=async()=>{if(!await askV6('シールガチャを引きますか？','無料でシールを1枚獲得します。'))return;const m=pick(D.monsters);state.stickers[m.name]=(state.stickers[m.name]||0)+1;save();gachaV6(root);showModal('シールを獲得！',`<div class="sticker-result">${stageArtMarkup(m)}<h2>${esc(m.name)}</h2><p>コレクションに追加しました。</p></div>`);};}
applyTestV6();
